#! /bin/bash
nohup nice python3 signatrix.py scan data/aen1.txt &
nohup nice python3 signatrix.py scan data/aen2.txt &
nohup nice python3 signatrix.py scan data/aen3.txt &
nohup nice python3 signatrix.py scan data/aen4.txt &
nohup nice python3 signatrix.py scan data/aen5.txt &
nohup nice python3 signatrix.py scan data/aen6.txt &
nohup nice python3 signatrix.py scan data/aen7.txt &
nohup nice python3 signatrix.py scan data/aen8.txt &
nohup nice python3 signatrix.py scan data/aen9.txt &
nohup nice python3 signatrix.py scan data/aen10.txt &
nohup nice python3 signatrix.py scan data/aen11.txt &
nohup nice python3 signatrix.py scan data/aen12.txt &
